services:
  yt-backend:
    build:
      context: .
    platform: linux/amd64
    ports:
      - 38000:80
  yt-ui:
    image: ytsaurus/ui:stable
    ports:
      - 30080:80
    environment:
      PROXY: localhost:38000
      PROXY_INTERNAL: host.docker.internal:38000
      APP_ENV: local
      APP_INSTALLATION: ""
