services:
  yt-backend:
    build:
      context: .
    platform: linux/amd64
    ports:
      - 38000:80
  yt-ui:
    image: ytsaurus/ui:stable
    ports:
      - 30080:80
    environment:
      PROXY: host.docker.internal:38000
      APP_INSTALLATION: "custom"
      ALLOW_PASSWORD_AUTH: "1"
      YT_AUTH_ALLOW_INSECURE: "1"
      YT_AUTH_CLUSTER_ID: "hegel"
    volumes:
      - ./ui/clusters-config.json:/opt/app/clusters-config.json
      - ./ui/yt-interface-secret.json:/opt/app/secrets/yt-interface-secret.json
