version = 2

[debug]
  level = "debug"

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    image_pull_progress_timeout = "5m0s"
    restrict_oom_score_adj = true
    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/usr/local/lib/cni"
      conf_dir = "/etc/cni/net.d"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          sandbox_mode = "podsandbox"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = false
