name: test-dockerfile

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "setup python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "install yt client"
        run: pip install ytsaurus-client ytsaurus-rpc-driver

      - name: "run test.sh"
        run: ./tests/test.sh
